#!/bin/bash

echo "Updacteum"

echo "Shutdown after updates?" \[Y\|N\]

read VAR2;
case "$VAR2" in
	n|N)
		sudo apt update

		sudo apt upgrade -y

		sudo snap refresh

		;;
	y|Y)

		sudo apt update

		sudo apt upgrade -y

		sudo snap refresh

		shutdown -h +1
		
		;;
	*)
		echo "Invalid"
		
		;;
	esac
